# Generated by Django 3.2.5 on 2022-07-05 10:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('crypto_name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Crypto')),
                ('ticker', models.CharField(max_length=20, unique=True, verbose_name='ticker')),
                ('abnormal_rets', models.IntegerField(default=0, verbose_name='Farma French')),
            ],
        ),
        migrations.CreateModel(
            name='Gdelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('crypto', models.CharField(max_length=20, verbose_name='Crypto')),
                ('url', models.CharField(max_length=1000, verbose_name='Url')),
                ('url_mobile', models.CharField(max_length=1000, verbose_name='Url mobile')),
                ('title', models.CharField(max_length=1000, verbose_name='Title')),
                ('seendate', models.CharField(max_length=1000, verbose_name='seendate')),
                ('socialimage', models.CharField(max_length=1000, verbose_name='image')),
                ('domain', models.CharField(max_length=1000, verbose_name='Domain')),
                ('language', models.CharField(max_length=1000, verbose_name='Language')),
                ('sourcecountry', models.CharField(max_length=1000, verbose_name='Countrysource')),
                ('finbert_positive', models.FloatField(default=None)),
                ('finbert_negative', models.FloatField(default=None)),
                ('final_finbert', models.FloatField(default=None)),
                ('fama_french', models.IntegerField(default=0)),
            ],
        ),
    ]
